name: workspace.tramvm.com
on:
  push:
    branches:
      - master
jobs:
  build_deploy:
    name: Workspace Website
    runs-on: self-hosted
    steps:
      - name: Echo path
        run: echo $PWD
      - uses: actions/checkout@master
      - uses: Copy source code
        run: |
          cp -rf /webapps/actions-runner/workspace.tramvm.com/workspace-tramvm-com/workspace-tramvm-com /webapps
          cd /webapps/workspace-tramvm-com
      - name: Build & Deploy docker
        env:
          name: prod
        run: |
          echo $PWD
          docker-compose up -d --build